/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Item: typeof import('./../components/item/item.vue')['default']
    PrivacyPopup: typeof import('./../components/privacy-popup/privacy-popup.vue')['default']
    ZDivider: typeof import('./../components/divider/ZDivider.vue')['default']
    ZNavbar: typeof import('./../components/navbar/ZNavbar.vue')['default']
  }
}
