/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZBtn: typeof import('./../../../shared/components/btn/ZBtn.vue')['default']
    ZBtnToggle: typeof import('./../../../shared/components/btn/ZBtnToggle.vue')['default']
    ZCaptchaInput: typeof import('./../../../shared/components/input/ZCaptchaInput.vue')['default']
    ZCascaderSelect: typeof import('./../../../shared/components/select/ZCascaderSelect.vue')['default']
    ZCheckbox: typeof import('./../../../shared/components/checkbox/ZCheckbox.vue')['default']
    ZCodeInput: typeof import('./../../../shared/components/input/ZCodeInput.vue')['default']
    ZDialog: typeof import('./../../../shared/components/dialog/ZDialog.vue')['default']
    ZDragUpload: typeof import('./../../../shared/components/upload/ZDragUpload.vue')['default']
    ZEmpty: typeof import('./../../../shared/components/empty/ZEmpty.vue')['default']
    ZIconBtn: typeof import('./../../../shared/components/btn/ZIconBtn.vue')['default']
    ZInfiniteSlider: typeof import('./../../../shared/components/slider/ZInfiniteSlider.vue')['default']
    ZInfo: typeof import('./../../../shared/components/info/ZInfo.vue')['default']
    ZInput: typeof import('./../../../shared/components/input/ZInput.vue')['default']
    ZInputNumRange: typeof import('./../../../shared/components/input/ZInputNumRange.vue')['default']
    ZLabel: typeof import('./../../../shared/components/label/ZLabel.vue')['default']
    ZLoading: typeof import('./../../../shared/components/loading/ZLoading.vue')['default']
    ZLoginTabs: typeof import('./../../../shared/components/tabs/ZLoginTabs.vue')['default']
    ZLogoutDialog: typeof import('./../../../shared/components/dialog/ZLogoutDialog.vue')['default']
    ZRadio: typeof import('./../../../shared/components/radio/ZRadio.vue')['default']
    ZReadonlyInput: typeof import('./../../../shared/components/input/ZReadonlyInput.vue')['default']
    ZRichtext: typeof import('./../../../shared/components/richtext/ZRichtext.vue')['default']
    ZSelect: typeof import('./../../../shared/components/select/ZSelect.vue')['default']
    ZStatus: typeof import('./../../../shared/components/status/ZStatus.vue')['default']
    ZTable: typeof import('./../../../shared/components/table/ZTable.vue')['default']
    ZTableFieldConfig: typeof import('./../../../shared/components/table/ZTableFieldConfig.vue')['default']
    ZTabs: typeof import('./../../../shared/components/tabs/ZTabs.vue')['default']
    ZTag: typeof import('./../../../shared/components/tag/ZTag.vue')['default']
    ZTextBtn: typeof import('./../../../shared/components/btn/ZTextBtn.vue')['default']
    ZToggle: typeof import('./../../../shared/components/toggle/ZToggle.vue')['default']
    ZUpload: typeof import('./../../../shared/components/upload/ZUpload.vue')['default']
  }
}
